name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
                  
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        version_format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
          
            
    - name: docker auth
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
        NEW_VERSION: ${{steps.version.outputs.version}}
      run: |
        echo "Iniciando Login..."
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN
        echo "Finalizando login."
        echo "version a utilizar: $NEW_VERSION!!!!!!!!!!!!!!!!!!"
    
    - name: Create Docker image
      run: |
        docker build -t tecnoin19/docker-graphql:$NEW_VERSION .
        docker build -t tecnoin19/docker-graphql:latest .

    - name: Push Docker image
      run: |
        docker push tecnoin19/docker-graphql:$NEW_VERSION
        docker push tecnoin19/docker-graphql:latest


      
                                                                                                      
    
    
    #- name: Build the Docker image
     # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
