name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: docker auth
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      run: |
        echo "Iniciando Login..."
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN
        echo "Finalizando login."
    
    - name: Create Docker image
      run: |
        docker build -t tecnoin19/docker-graphql:0.0.2 .

    - name: Push Docker image
      run: |
        docker push tecnoin19/docker-graphql:0.0.2


      
                                                                                                      
    
    
    #- name: Build the Docker image
     # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
